version: "3.8"
services:
  api:
    build: ./api
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - "4000:4000"

  web:
    build: ./web
    ports:
      - "3000:3000"
