version: "3.8"
services:
  api:
    build: ./api
    environment:
      DATABASE_URL: mongodb://localhost:27017/dash_skins_api_db
    ports:
      - "4000:4000"

  web:
    build: ./web
    ports:
      - "3000:3000"
